config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  scope '/:locale' do
    root to: 'home#index'

    get 'home/index'

    get 'styles/atoms'

    get 'styles/molecules'

    get 'styles/organisms'

    get 'styleguide', to: 'styles#atoms'

    get 'complete/style/guide', to: 'styles#atoms'

    resources :sessions, only: [:new, :create, :destroy]

    resources :users, only: [:new, :create, :edit, :update] do
      resources :goals
    end


    resources :ideas do
      resources :comments
      resources :photos
    end

    get 'account', to: 'account#edit'
    patch 'account', to: 'account#update'
    get 'account/ideas'
    get 'account/goals'

    get 'login', to: 'sessions#new'

    get 'signup', to: 'users#new'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 75 }

  belongs_to :user

  has_many :comments

  has_and_belongs_to_many :users


  # Change the follwing Idea table method to scope most recent below
  # def self.most_recent()
  #   all.order(created_at: :desc).limit(3)
  # end

  scope :most_recent,          -> { order(created_at: :desc).limit(3) }
  scope :title_contains,       ->(item) { where('title LIKE ?', "%#{item}%") }
  scope :description_contains, ->(item) { where('description LIKE ?', "%#{item}%") }

  scope :search,               ->(search_term) { title_contains(search_term).or(description_contains(search_term)) }

  paginates_per 9

  # The following search is modified as the search scope above
  # def self.search(search_term)
  #   wildcard_filter = "%#{search_term}%"
  #   where('title LIKE ?', wildcard_filter).or(where('description LIKE ?', wildcard_filter))
  # end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  include RolesHelper

  before_action :ensure_authenticated,   only: [:new, :create, :edit, :update]
  before_action :load_idea,              only: [:edit, :update, :destroy]
  before_action :authorize_to_edit_idea, only: [:edit, :update, :destroy]
  # before_action :ensure_owner,         only: [:edit, :update]

  def index
    @search_term = params[:q]
    logger.info("Search completed using #{@search_term}.")
    @ideas = Idea.search(@search_term).page(params[:page])
  end

  def show
    @idea = Idea.find(params[:id])
    @comment = Comment.new
    @display_add_comment = session[:user_id].present?

    if(logged_in?)
      @disable_add_goal = current_user.goals.exists?(@idea.id)
    end
  end

  def new
    @idea = Idea.new
  end

  def create
    user = User.find(session[:user_id])
    @idea = Idea.new(idea_resource_params)
    @idea.user = user
    if(@idea.save)
      redirect_to ideas_path
    else
      render 'new'
    end
  end

  def edit
    # Remove the following two lines after using @idea in ensure_owner method
    # id = params[:id]
    # @idea = Idea.find(id)
  end

  def update
    # Remove the following line after using @idea in ensure_owner method
    # @idea = Idea.find(params[:id])
    if(@idea.update(idea_resource_params))
      redirect_to account_ideas_path
    else
      render 'edit'
    end
  end

  def destroy
    @idea.destroy!
  end

  private

  def idea_resource_params
    params.require(:idea).permit(:title, :description, :photo_url, :done_count)
  end

  def load_idea
    #make sure before:action to load idea above
    @idea = Idea.find(params[:id])
  end

  # def ensure_owner
  #   redirect_to(account_path) unless(can_edit?(@idea))
  # end

  #Change the method name from ensure_owner to authorize_to_edit_idea

  def authorize_to_edit_idea
    redirect_to(account_path) unless(can_edit?(@idea))
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<% if(idea.errors.any?) %>
  <div class="alert alert--wide">
    <%= idea.errors.full_messages.join('<br />') %>
  </div>
<% end %>
<%= form_for(idea, html: { class: 'form--inpage' }) do |form| %>
  <div class="input-group input-group--horizontal">
    <%= form.label(:title, class: 'input-group__label') %>
    <%= form.text_field(:title, placeholder:'E.g. Ride a camel', class: 'input-group__field' ) %>
  </div>

  <div class="input-group input-group--horizontal">
    <%= form.label(:done_count, class: 'input-group__label') %>
    <%= form.text_field(:done_count, class: 'input-group__field') %>
  </div>

  <div class="input-group input-group--horizontal">
    <%= form.label(:photo_url, class: 'input-group__label') %>
    <%= form.text_field(:photo_url, class: 'input-group__field') %>
  </div>

  <div class="input-group input-group--horizontal">
    <%= form.label(:description, class: 'input-group__label') %>
    <%= form.text_area(:description, class: 'input-group__field') %>
  </div>

  <div class="prompt">
    <a class="prompt__cancel" href="#cancel">Cancel</a>

    <%= form.submit(class: 'btn btn--primary prompt__confirm') %>

  </div>
<% end %>

app/views/ideas/destroy.js.erb
// document.getElementById("idea-<%= @idea.id %>").parentElement.remove();
// We can use <%= @idea.id %>" here but not in js script
Ideas.removeIdeaCard("<%= @idea.id %>");

app/views/ideas/edit.html.erb
<main>
  <div class="content-wrapper">
    <nav>
      <ul class="sub-navigation">
        <li><a href="#nolink" class="current">Idea</a></li>
        <li><%= link_to('Photos', idea_photos_path(@idea)) %></li>
      </ul>
    </nav>
    <h1>Edit idea</h1>
    <%= render(partial: 'form', locals: { idea: @idea }) %>
  </div>
</main>

app/views/ideas/edit_backup.html.erb
<main>
  <div class="content-wrapper">
    <h1>Edit idea</h1>
    <%= render(partial: 'form', locals: { idea: @idea }) %>
  </div>
</main>

app/views/ideas/index.html.erb
<main>
  <div class="content-wrapper">
    <h1>Results for "<%= @search_term %>"</h1>
  </div>
  <div class="content-wrapper">
    <% if(@ideas.any?) %>
      <ul class="bare-list float-grid css-grid">
        <% @ideas.each do |idea| %>
          <li>
            <%= render(partial: 'idea_card',
                       locals: { card_title: idea.title, done_count: idea.done_count, photo_url: idea.photo_url, idea: idea }) %>
          </li>
        <% end %>
      </ul>
    <div class="see-more">
      <%= paginate @ideas %>
    </div>
    <% else %>
      <h3>No ideas found!</h3>
    <% end %>
  </div>
</main>

app/views/ideas/index_backup.html.erb
<main>
  <div class="content-wrapper">
    <h1>Results for "<%= @search_term %>"</h1>
  </div>
  <div class="content-wrapper">
    <% if(@ideas.any?) %>
      <ul class="bare-list float-grid css-grid">
        <% @ideas.each do |idea| %>
          <li>
            <%= render(partial: 'idea_card',
                       locals: { card_title: idea.title, done_count: idea.done_count, photo_url: idea.photo_url, idea: idea }) %>
          </li>
        <% end %>
      </ul>
    <div class="see-more">
      <button class="btn" type="button" data-more="true">See more</button>
    </div>
    <% else %>
      <h3>No ideas found!</h3>
    <% end %>
  </div>
</main>

app/views/ideas/new.html.erb
<main>
  <div class="content-wrapper">
    <h1>Create new idea</h1>
    <%= render(partial: 'form', locals: { idea: @idea }) %>
  </div>
</main>

app/views/ideas/show.html.erb
<main>
  <div class="content-wrapper hr">
    <div class="media">
      <div class="media__figure">
        <%= render(partial: 'idea_photo', locals: { photo_url: @idea.photo_url }) %>
      </div>
      <div class="media__body">
        <div class="goal">
          <div class="goal__owner">
            <%= image_tag('/images/avatar.png', alt: "Default avatar") %>
            <!-- <img class="avatar" src="#images/avatar.png" alt="Portrait of Frederick Rose"> -->
            <p>Created by <a href="#">Frederick Rose</a></p>
          </div>
          <h1 class="gamma"><%= @idea.title %></h1>
          <ul class="horizontal-list btn-group">
            <li>
              <%= link_to(edit_idea_path(@idea), class: 'btn delta') do %>
                <svg class="icon-check icon--sm" role="presentation">
                  <!-- <use xlink:href="images/icons-defs.svg#check"></use> -->
                </svg>
                Edit
              <% end %>
            </li>
            <li>
              <% if(logged_in?) %>
                <%= form_tag(user_goals_path(current_user)) do %>
                  <%= hidden_field_tag('idea_id', @idea.id) %>
                  <%= button_tag(class: 'btn delta', type: 'submit', disabled: @disable_add_goal) do %>
                    <svg class="icon-heart icon--sm" role="presentation">
                      <!-- <use xlink:href="images/icons-defs.svg#heart"></use> -->
                    </svg>
                    Add
                  <% end %>
                <% end %>
              <% end %>
            </li>
          </ul>
          <div class="goal__intro">
            <p><%= @idea.description %></p>
          </div>
          <div class="goal__meta">
            <span>Created on <time datetime="2017-08-27T03:48"><%= @idea.created_at.strftime("%d %b '%y") %></time></span>
            <span><%= @idea.done_count %> have done this</span>
            <span><a href="#comments">3 comments</a></span>
          </div>
          <ul class="tags-list">
            <li><a href="#nature">Nature</a></li>
            <li><a href="#swimming">Swimming</a></li>
            <li>
              <a href="#travel" class="selected">
                Travel
                <i class="remove-tag">&times;</i>
              </a>
            </li>
            <li><a href="#tag4" data-filter="tag-4">Tag 4</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="content-wrapper">
    <div class="comments">
      <h2 class="comments__title">Discussion <span>3 comments</span></h2>
      <% if(@display_add_comment) %>
        <%= form_for([@idea, @comment], html: { class: 'comments__input'}, remote: true) do |form| %>
          <img class="avatar" src="#images/avatar.png" alt="Portrait of logged in user">
          <div class="input-group">
            <%= form.label(:body, 'Add a comment', class: 'input-group__label') %>
            <%= form.text_area(:body, class: 'input-group__field') %>
          </div>
          <%= form.submit('Post', class: 'btn btn--primary') %>
        <% end %>
      <% end %>

      <ul class="comments__listing" id="commentList">
        <% @idea.comments.each do |comment| %>
        <li class="comment">
          <%= image_tag('/images/avatar.png', alt: "Default avatar") %>
          <!-- <img class="avatar" src="#images/avatar.png" alt="Portrait of commenter"> -->
          <div class="comment__body">
            <h3 class="comment__title">Tom Jenkinson <time datetime="2017-08-28T13:48">Today</time></h3>
            <p><%= comment.body %></p>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</main>

app/views/ideas/show_backup.html.erb
<main>
  <div class="content-wrapper hr">
    <div class="media">
      <div class="media__figure">
        <%= render(partial: 'idea_photo', locals: { photo_url: @idea.photo_url }) %>
      </div>
      <div class="media__body">
        <div class="goal">
          <div class="goal__owner">
            <%= image_tag('/images/avatar.png', alt: "Default avatar") %>
            <!-- <img class="avatar" src="#images/avatar.png" alt="Portrait of Frederick Rose"> -->
            <p>Created by <a href="#">Frederick Rose</a></p>
          </div>
          <h1 class="gamma"><%= @idea.title %></h1>
          <ul class="horizontal-list btn-group">
            <li>
              <%= link_to(edit_idea_path(@idea), class: 'btn delta') do %>
                <svg class="icon-check icon--sm" role="presentation">
                  <!-- <use xlink:href="images/icons-defs.svg#check"></use> -->
                </svg>
                Edit
              <% end %>
            </li>
            <li>
              <% if(@user.present?) %>
                <%= form_tag(user_goals_path(@user)) do %>
                  <%= hidden_field_tag('idea_id', @idea.id) %>
                  <%= button_tag(class: 'btn delta', type: 'submit', disabled: @disable_add_goal) do %>
                    <svg class="icon-heart icon--sm" role="presentation">
                      <!-- <use xlink:href="images/icons-defs.svg#heart"></use> -->
                    </svg>
                    Add
                  <% end %>
                <% end %>
              <% end %>
            </li>
          </ul>
          <div class="goal__intro">
            <p><%= @idea.description %></p>
          </div>
          <div class="goal__meta">
            <span>Created on <time datetime="2017-08-27T03:48"><%= @idea.created_at.strftime("%d %b '%y") %></time></span>
            <span><%= @idea.done_count %> have done this</span>
            <span><a href="#comments">3 comments</a></span>
          </div>
          <ul class="tags-list">
            <li><a href="#nature">Nature</a></li>
            <li><a href="#swimming">Swimming</a></li>
            <li>
              <a href="#travel" class="selected">
                Travel
                <i class="remove-tag">&times;</i>
              </a>
            </li>
            <li><a href="#tag4" data-filter="tag-4">Tag 4</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="content-wrapper">
    <div class="comments">
      <h2 class="comments__title">Discussion <span>3 comments</span></h2>
      <% if(@display_add_comment) %>
        <%= form_for([@idea, @comment], html: { class: 'comments__input'}) do |form| %>
          <img class="avatar" src="#images/avatar.png" alt="Portrait of logged in user">
          <div class="input-group">
            <%= form.label(:body, 'Add a comment', class: 'input-group__label') %>
            <%= form.text_area(:body, class: 'input-group__field') %>
          </div>
          <%= form.submit('Post', class: 'btn btn--primary') %>
        <% end %>
      <% end %>

      <ul class="comments__listing">
        <% @idea.comments.each do |comment| %>
        <li class="comment">
          <%= image_tag('/images/avatar.png', alt: "Default avatar") %>
          <!-- <img class="avatar" src="#images/avatar.png" alt="Portrait of commenter"> -->
          <div class="comment__body">
            <h3 class="comment__title">Tom Jenkinson <time datetime="2017-08-28T13:48">Today</time></h3>
            <p><%= comment.body %></p>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</main>

app/views/ideas/show_backup2.html.erb
<main>
  <div class="content-wrapper hr">
    <div class="media">
      <div class="media__figure">
        <%= render(partial: 'idea_photo', locals: { photo_url: @idea.photo_url }) %>
      </div>
      <div class="media__body">
        <div class="goal">
          <div class="goal__owner">
            <%= image_tag('/images/avatar.png', alt: "Default avatar") %>
            <!-- <img class="avatar" src="#images/avatar.png" alt="Portrait of Frederick Rose"> -->
            <p>Created by <a href="#">Frederick Rose</a></p>
          </div>
          <h1 class="gamma"><%= @idea.title %></h1>
          <ul class="horizontal-list btn-group">
            <li>
              <%= link_to(edit_idea_path(@idea), class: 'btn delta') do %>
                <svg class="icon-check icon--sm" role="presentation">
                  <!-- <use xlink:href="images/icons-defs.svg#check"></use> -->
                </svg>
                Edit
              <% end %>
            </li>
            <li>
              <% if(@user.present?) %>
                <%= form_tag(user_goals_path(@user)) do %>
                  <%= hidden_field_tag('idea_id', @idea.id) %>
                  <%= button_tag(class: 'btn delta', type: 'submit', disabled: @disable_add_goal) do %>
                    <svg class="icon-heart icon--sm" role="presentation">
                      <!-- <use xlink:href="images/icons-defs.svg#heart"></use> -->
                    </svg>
                    Add
                  <% end %>
                <% end %>
              <% end %>
            </li>
          </ul>
          <div class="goal__intro">
            <p><%= @idea.description %></p>
          </div>
          <div class="goal__meta">
            <span>Created on <time datetime="2017-08-27T03:48"><%= @idea.created_at.strftime("%d %b '%y") %></time></span>
            <span><%= @idea.done_count %> have done this</span>
            <span><a href="#comments">3 comments</a></span>
          </div>
          <ul class="tags-list">
            <li><a href="#nature">Nature</a></li>
            <li><a href="#swimming">Swimming</a></li>
            <li>
              <a href="#travel" class="selected">
                Travel
                <i class="remove-tag">&times;</i>
              </a>
            </li>
            <li><a href="#tag4" data-filter="tag-4">Tag 4</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="content-wrapper">
    <div class="comments">
      <h2 class="comments__title">Discussion <span>3 comments</span></h2>
      <% if(@display_add_comment) %>
        <%= form_for([@idea, @comment], html: { class: 'comments__input'}, remote: true) do |form| %>
          <img class="avatar" src="#images/avatar.png" alt="Portrait of logged in user">
          <div class="input-group">
            <%= form.label(:body, 'Add a comment', class: 'input-group__label') %>
            <%= form.text_area(:body, class: 'input-group__field') %>
          </div>
          <%= form.submit('Post', class: 'btn btn--primary') %>
        <% end %>
      <% end %>

      <ul class="comments__listing" id="commentList">
        <% @idea.comments.each do |comment| %>
        <li class="comment">
          <%= image_tag('/images/avatar.png', alt: "Default avatar") %>
          <!-- <img class="avatar" src="#images/avatar.png" alt="Portrait of commenter"> -->
          <div class="comment__body">
            <h3 class="comment__title">Tom Jenkinson <time datetime="2017-08-28T13:48">Today</time></h3>
            <p><%= comment.body %></p>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</main>