config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  scope '/:locale' do
    root to: 'home#index'

    get 'home/index'

    get 'styles/atoms'

    get 'styles/molecules'

    get 'styles/organisms'

    get 'styleguide', to: 'styles#atoms'

    get 'complete/style/guide', to: 'styles#atoms'

    resources :sessions, only: [:new, :create, :destroy]

    resources :users, only: [:new, :create, :edit, :update] do
      resources :goals
    end


    resources :ideas do
      resources :comments
      resources :photos
    end

    get 'account', to: 'account#edit'
    patch 'account', to: 'account#update'
    get 'account/ideas'
    get 'account/goals'

    get 'login', to: 'sessions#new'

    get 'signup', to: 'users#new'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idea
  belongs_to :user
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 75 }

  belongs_to :user

  has_many :comments

  has_and_belongs_to_many :users


  # Change the follwing Idea table method to scope most recent below
  # def self.most_recent()
  #   all.order(created_at: :desc).limit(3)
  # end

  scope :most_recent,          -> { order(created_at: :desc).limit(3) }
  scope :title_contains,       ->(item) { where('title LIKE ?', "%#{item}%") }
  scope :description_contains, ->(item) { where('description LIKE ?', "%#{item}%") }

  scope :search,               ->(search_term) { title_contains(search_term).or(description_contains(search_term)) }

  paginates_per 9

  # The following search is modified as the search scope above
  # def self.search(search_term)
  #   wildcard_filter = "%#{search_term}%"
  #   where('title LIKE ?', wildcard_filter).or(where('description LIKE ?', wildcard_filter))
  # end
end

app/models/idea_backup.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 75 }

  belongs_to :user

  has_many :comments

  has_and_belongs_to_many :users

  def self.most_recent()
    all.order(created_at: :desc).limit(3)
  end

  def self.search(search_term)
    wildcard_filter = "%#{search_term}%"
    where('title LIKE ?', wildcard_filter).or(where('description LIKE ?', wildcard_filter))
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :ideas
  has_and_belongs_to_many :goals, class_name: 'Idea'

  has_secure_password

  validates :email, uniqueness: true
  validates :role, inclusion: { in: %w(registered admin) }


  after_initialize :default_role!
  before_validation :downcase_email

  mount_uploader :avatar, AvatarUploader

  private

  def downcase_email
    self.email = email.downcase
  end

  def default_role!
    self.role ||= 'registered'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  helper_method :logged_in?, :current_user

  before_action:set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def logged_in?
      session[:user_id].present?
  end

  def current_user
    if(@current_user.present?)
      return @current_user
    end

    @current_user = User.find(session[:user_id])
  end

  def ensure_authenticated
    redirect_to login_path unless(logged_in?)
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :ensure_authenticated

  def create
    @idea = Idea.find(params[:idea_id])

    current_user.goals << @idea

    respond_to do |format|
      format.html { redirect_to idea_path(idea) }
      format.js
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ideas = Idea.most_recent
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  include RolesHelper

  before_action :ensure_authenticated,   only: [:new, :create, :edit, :update]
  before_action :load_idea,              only: [:edit, :update, :destroy]
  before_action :authorize_to_edit_idea, only: [:edit, :update, :destroy]
  # before_action :ensure_owner,         only: [:edit, :update]

  def index
    @search_term = params[:q]
    logger.info("Search completed using #{@search_term}.")
    @ideas = Idea.search(@search_term).page(params[:page])
  end

  def show
    @idea = Idea.find(params[:id])
    @comment = Comment.new
    @display_add_comment = session[:user_id].present?

    if(logged_in?)
      @disable_add_goal = current_user.goals.exists?(@idea.id)
    end
  end

  def new
    @idea = Idea.new
  end

  def create
    user = User.find(session[:user_id])
    @idea = Idea.new(idea_resource_params)
    @idea.user = user
    if(@idea.save)
      redirect_to ideas_path
    else
      render 'new'
    end
  end

  def edit
    # Remove the following two lines after using @idea in ensure_owner method
    # id = params[:id]
    # @idea = Idea.find(id)
  end

  def update
    # Remove the following line after using @idea in ensure_owner method
    # @idea = Idea.find(params[:id])
    if(@idea.update(idea_resource_params))
      redirect_to account_ideas_path
    else
      render 'edit'
    end
  end

  def destroy
    @idea.destroy!
  end

  private

  def idea_resource_params
    params.require(:idea).permit(:title, :description, :photo_url, :done_count)
  end

  def load_idea
    #make sure before:action to load idea above
    @idea = Idea.find(params[:id])
  end

  # def ensure_owner
  #   redirect_to(account_path) unless(can_edit?(@idea))
  # end

  #Change the method name from ensure_owner to authorize_to_edit_idea

  def authorize_to_edit_idea
    redirect_to(account_path) unless(can_edit?(@idea))
  end
end

app/controllers/temp.rb
def create
  idea = Idea.new
  idea.title = params[:title]
  idea.done_count = params[:done_count]
  idea.photo_url = params[:photo_url]
  idea.save!
  redirect_to ideas_path
end


def create
  hash = { title: params[:title],
           done_count: params[:done_count],
           description: params[:description],
           photo_url: params[:photo_url] }
  idea = Idea.new(hash)
  idea.save!
  redirect_to ideas_path
end

def update
  idea = Idea.find (params[:id])
  idea.title = params[:title]
  idea.done_count = params[:done_count]
  idea.photo_url = params[:photo_url]
  idea.save!
  redirect_to account_ideas_path
end

def update
  hash = { title: params[:title],
           done_count: params[:done_count],
           description: params[:description],
           photo_url: params[:photo_url] }
  idea = Idea.last()
  idea.update(hash)
  redirect_to account_ideas_path
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_admin, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if(@user.save)
      session[:user_id] = @user.id
      redirect_to ideas_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]

    if(@user.update(edit_user_parems))
      redirect_to account_path
    else
      render 'edit'
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def edit_user_params
    params.require(:user).permit(:email, :name, :role)
  end

  def ensure_admin
    if(current_user.role == 'admin')
      return
    end

    redirect_to account_path
  end

end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def
  #   can_edit?(goal)
  #   case(current_user.role)
  #   when 'admin' then true
  #   when 'registered' then current_user == goal.user
  #   else false
  #   end
  # end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
  #moved from application helper
  def
    can_edit?(goal)
    case(current_user.role)
    when 'admin' then true
    when 'registered' then current_user == goal.user
    else false
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_anonymous_user_header.html.erb
<nav class="site-header__nav">
  <ul class="main-navigation">
    <li><a href="#nolink"><%= translate('inspiration') %></a></li>
    <li><%= link_to(translate('signup'), signup_path) %></li>
    <li><%= link_to(translate('login'), login_path) %></li>
  </ul>
</nav>

app/views/application/_authenticated_user_header.html.erb
<nav class="site-header__nav">
  <ul class="main-navigation">
    <li><a href="#nolink"><%= translate('inspiration') %></a></li>
    <li><%= link_to(translate('account'), account_ideas_path) %></li>
    <li><%= link_to(translate('logout'), session_path(1), method: :delete) %></li>
  </ul>
</nav>

app/views/application/_button.html.erb
<button class="btn" type="button"><%= label %></button>

app/views/application/_idea_card.html.erb
<div class="card">
  <div class="card__thumb">
    <%= link_to(idea_path(idea)) do %>
      <%= render(partial: 'idea_photo', locals: { photo_url: photo_url }) %>
    <% end %>
    <div class="card__intro">
      <h4 class="card__title"><%= card_title %></h4>
      <span><%= done_count %> have done this </span>
    </div>
  </div>
  <div class="card__footer">
    <button class="card__btn card__like delta" data-like="see-the-northern-lights">
      <svg class="icon-heart icon-heart--liked" role="presentation">
        <!-- <use xlink:href="images/icons-defs.svg#heart"></use> -->
        <use href="<%= image_path('icons/icons-defs.svg') %>#heart"></use>
      </svg>
      Like
    </button>
    <% if(logged_in?) %>
      <%= form_tag(user_goals_path(current_user), remote: true, id: "goal-#{idea.id}") do %>
        <%= hidden_field_tag('idea_id', idea.id) %>
        <%= button_tag(class: 'btn delta', type: 'submit') do %>
          <svg class="icon-pluss icon--sm" role="presentation">
            <use xlink:href="<%= asset_url("icons/icons-defs.svg" + "#pluss")%>"</use>
          </svg>
          Add Goal
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/application/_idea_card_backup.html.erb
<div class="card">
  <div class="card__thumb">
    <%= link_to(idea_path(idea)) do %>
      <%= render(partial: 'idea_photo', locals: { photo_url: photo_url }) %>
    <% end %>
    <div class="card__intro">
      <h4 class="card__title"><%= card_title %></h4>
      <span><%= done_count %> have done this </span>
    </div>
  </div>
  <div class="card__footer">
    <button class="card__btn card__like delta" data-like="see-the-northern-lights">
      <svg class="icon-heart icon-heart--liked" role="presentation">
        <!-- <use xlink:href="images/icons-defs.svg#heart"></use> -->
        <use href=<%= image_path('icons/icons-defs.svg') %>#heart"></use>
      </svg>
      Like
    </button>
    <button class="card__btn card__add delta" data-addGoal="see-the-northern-lights">
      <svg class="icon-pluss" role="presentation">
        <!-- <use xlink:href="images/icons-defs.svg#pluss"></use> -->
        <use href=<%= image_path('icons/icons-defs.svg') %>#plus"></use>
      </svg>
      Add Goal
    </button>
  </div>
</div>

app/views/application/_idea_photo.html.erb
<% if(photo_url.nil?) %>
  <img src="http://fpoimg.com/255x170"
   alt="Northern lights over mountain covered in snow">
<% else %>
  <%= image_tag(photo_url) %>
<% end %>

app/views/application/_link_button.html.erb
<a class="btn" href="#nolink"><%= label %></a>

app/views/application/_logo.html.erb
<div class="logo">
  <a href="/"><span><i>My</i> Bucket List</span></a>
</div>

app/views/application/_negative_button.html.erb
<button class="btn btn--warning" type="button"><%= label %></button>

app/views/application/_negative_logo.html.erb
<div class="sg-dark-bg">
  <div class="logo logo--inverted footer__logo">
    <a href="/"><span><i>My</i> Bucket List</span></a>
  </div>
</div>

app/views/application/_primary_button.html.erb
<button class="btn btn--primary" type="button"><%= label %></button>

app/views/application/_prompt_buttons.html.erb
<div class="prompt">
  <a class="prompt__cancel" href="#cancel">Cancel</a>
  <button class="btn btn--primary prompt__confirm" type="submit"><%= label %></button>
</div>

app/views/application/_search_control.html.erb
<div class="input-inline">
  <label class="input-group__label" for="global-search-input">Looking for inspiration?</label>
  <div class="input-row">
    <input id="global-search-input" class="input-row__field" type="text" name="global-search" placeholder="e.g. Swimming with dolphins">
    <button class="btn btn--inline" type="submit">Search</button>
  </div>
</div>

app/views/application/_search_form.html.erb
<%= form_tag(ideas_path, class: 'global-search', method: 'GET') do %>
  <div class="input-inline">
    <label class="input-group__label sr-only" for="q">Looking for inspiration?</label>
    <div class="input-row">
      <%= text_field_tag('q', nil, class: 'input-row__field', placeholder: 'e.g. Swimming with dolphins') %>

      <%= button_tag('Search', class: 'btn btn--inline btn--primary')  %>
    </div>
  </div>
<% end %>