config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  scope '/:locale' do
    root to: 'home#index'

    get 'home/index'

    get 'styles/atoms'

    get 'styles/molecules'

    get 'styles/organisms'

    get 'styleguide', to: 'styles#atoms'

    get 'complete/style/guide', to: 'styles#atoms'

    resources :sessions, only: [:new, :create, :destroy]

    resources :users, only: [:new, :create, :edit, :update] do
      resources :goals
    end


    resources :ideas do
      resources :comments
      resources :photos
    end

    get 'account', to: 'account#edit'
    patch 'account', to: 'account#update'
    get 'account/ideas'
    get 'account/goals'

    get 'login', to: 'sessions#new'

    get 'signup', to: 'users#new'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idea
  belongs_to :user
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 75 }

  belongs_to :user

  has_many :comments

  has_and_belongs_to_many :users


  # Change the follwing Idea table method to scope most recent below
  # def self.most_recent()
  #   all.order(created_at: :desc).limit(3)
  # end

  scope :most_recent,          -> { order(created_at: :desc).limit(3) }
  scope :title_contains,       ->(item) { where('title LIKE ?', "%#{item}%") }
  scope :description_contains, ->(item) { where('description LIKE ?', "%#{item}%") }

  scope :search,               ->(search_term) { title_contains(search_term).or(description_contains(search_term)) }

  paginates_per 9

  # The following search is modified as the search scope above
  # def self.search(search_term)
  #   wildcard_filter = "%#{search_term}%"
  #   where('title LIKE ?', wildcard_filter).or(where('description LIKE ?', wildcard_filter))
  # end
end

app/models/idea_backup.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 75 }

  belongs_to :user

  has_many :comments

  has_and_belongs_to_many :users

  def self.most_recent()
    all.order(created_at: :desc).limit(3)
  end

  def self.search(search_term)
    wildcard_filter = "%#{search_term}%"
    where('title LIKE ?', wildcard_filter).or(where('description LIKE ?', wildcard_filter))
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :ideas
  has_and_belongs_to_many :goals, class_name: 'Idea'

  has_secure_password

  validates :email, uniqueness: true
  validates :role, inclusion: { in: %w(registered admin) }


  after_initialize :default_role!
  before_validation :downcase_email

  mount_uploader :avatar, AvatarUploader

  private

  def downcase_email
    self.email = email.downcase
  end

  def default_role!
    self.role ||= 'registered'
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :ensure_authenticated

  def create
    @idea = Idea.find(params[:idea_id])

    current_user.goals << @idea

    respond_to do |format|
      format.html { redirect_to idea_path(idea) }
      format.js
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ideas = Idea.most_recent
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  include RolesHelper

  before_action :ensure_authenticated,   only: [:new, :create, :edit, :update]
  before_action :load_idea,              only: [:edit, :update, :destroy]
  before_action :authorize_to_edit_idea, only: [:edit, :update, :destroy]
  # before_action :ensure_owner,         only: [:edit, :update]

  def index
    @search_term = params[:q]
    logger.info("Search completed using #{@search_term}.")
    @ideas = Idea.search(@search_term).page(params[:page])
  end

  def show
    @idea = Idea.find(params[:id])
    @comment = Comment.new
    @display_add_comment = session[:user_id].present?

    if(logged_in?)
      @disable_add_goal = current_user.goals.exists?(@idea.id)
    end
  end

  def new
    @idea = Idea.new
  end

  def create
    user = User.find(session[:user_id])
    @idea = Idea.new(idea_resource_params)
    @idea.user = user
    if(@idea.save)
      redirect_to ideas_path
    else
      render 'new'
    end
  end

  def edit
    # Remove the following two lines after using @idea in ensure_owner method
    # id = params[:id]
    # @idea = Idea.find(id)
  end

  def update
    # Remove the following line after using @idea in ensure_owner method
    # @idea = Idea.find(params[:id])
    if(@idea.update(idea_resource_params))
      redirect_to account_ideas_path
    else
      render 'edit'
    end
  end

  def destroy
    @idea.destroy!
  end

  private

  def idea_resource_params
    params.require(:idea).permit(:title, :description, :photo_url, :done_count)
  end

  def load_idea
    #make sure before:action to load idea above
    @idea = Idea.find(params[:id])
  end

  # def ensure_owner
  #   redirect_to(account_path) unless(can_edit?(@idea))
  # end

  #Change the method name from ensure_owner to authorize_to_edit_idea

  def authorize_to_edit_idea
    redirect_to(account_path) unless(can_edit?(@idea))
  end
end

app/controllers/temp.rb
def create
  idea = Idea.new
  idea.title = params[:title]
  idea.done_count = params[:done_count]
  idea.photo_url = params[:photo_url]
  idea.save!
  redirect_to ideas_path
end


def create
  hash = { title: params[:title],
           done_count: params[:done_count],
           description: params[:description],
           photo_url: params[:photo_url] }
  idea = Idea.new(hash)
  idea.save!
  redirect_to ideas_path
end

def update
  idea = Idea.find (params[:id])
  idea.title = params[:title]
  idea.done_count = params[:done_count]
  idea.photo_url = params[:photo_url]
  idea.save!
  redirect_to account_ideas_path
end

def update
  hash = { title: params[:title],
           done_count: params[:done_count],
           description: params[:description],
           photo_url: params[:photo_url] }
  idea = Idea.last()
  idea.update(hash)
  redirect_to account_ideas_path
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def
  #   can_edit?(goal)
  #   case(current_user.role)
  #   when 'admin' then true
  #   when 'registered' then current_user == goal.user
  #   else false
  #   end
  # end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
  #moved from application helper
  def
    can_edit?(goal)
    case(current_user.role)
    when 'admin' then true
    when 'registered' then current_user == goal.user
    else false
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BucketList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <!-- <link rel="stylesheet" href="/css/main.css"></link> -->
    <!-- <link rel="stylesheet" href="css/styleguide.css"></link> -->
  </head>

  <body>

    <header class="sg-header">
      <div class="site-header">
        <div class="content-wrapper">
          <div class="logo">
            <%= link_to('<span><i>My</i> Bucket List</span>'.html_safe, root_path) %>
          </div>

          <%= render(partial: 'search_form')  %>
          <% if(logged_in?) %>
            <%= render(partial: 'authenticated_user_header') %>
          <% else %>
            <%= render(partial: 'anonymous_user_header') %>
          <% end %>
        </div>
      </div>
    </header>

    <%= yield %>

    <footer class="site-footer">
      <div class="content-wrapper">
        <div class="logo logo--inverted footer__logo">
          <%= link_to('<span><i>My</i> Bucket List</span>'.html_safe, root_path) %>
        </div>
        <nav class="footer__navigation">
          <ul>
            <li><a href="#nolink">About</a></li>
            <li><%= link_to('Style Guide', styles_atoms_path) %></li>
            <li><a href="#nolink">Terms of Use</a></li>
          </ul>
        </nav>
    
        <div>
          <% I18n.available_locales.each do |locale| %>
            <%= link_to locale, url_for(locale: locale) %>
          <% end %>
          <p class="copyright">&copy; EPFL 2017</p>
        </div>
      </div>
    </footer>



  </body>
</html>

app/views/layouts/application_backup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BucketList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>

    <!-- <link rel="stylesheet" href="/css/main.css"></link> -->
    <!-- <link rel="stylesheet" href="css/styleguide.css"></link> -->
  </head>

  <body>

    <header class="sg-header">
      <div class="site-header">
        <div class="content-wrapper">
          <div class="logo">


            <%= link_to('<span><i>My</i> Bucket List</span>'.html_safe, root_path) %>


          </div>

          <%= render(partial: 'search_form')  %>

          <nav class="site-header__nav">
            <ul class="main-navigation">
              <li><a href="#nolink">Inspiration</a></li>
              <li><%= link_to('Account', account_ideas_path) %></li>
              <li><a href="#nolink">Log In</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

    <%= yield %>

    <footer class="site-footer">
      <div class="content-wrapper">
        <div class="logo logo--inverted footer__logo">
          <%= link_to('<span><i>My</i> Bucket List</span>'.html_safe, root_path) %>
        </div>
        <nav class="footer__navigation">
          <ul>
            <li><a href="#nolink">About</a></li>
            <li><%= link_to('Style Guide', styles_atoms_path) %></li>
            <li><a href="#nolink">Terms of Use</a></li>
          </ul>
        </nav>
        <p class="copyright">&copy; EPFL 2017</p>
      </div>
    </footer>



  </body>
</html>

app/views/layouts/application_backup2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BucketList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <!-- <link rel="stylesheet" href="/css/main.css"></link> -->
    <!-- <link rel="stylesheet" href="css/styleguide.css"></link> -->
  </head>

  <body>

    <header class="sg-header">
      <div class="site-header">
        <div class="content-wrapper">
          <div class="logo">
            <%= link_to('<span><i>My</i> Bucket List</span>'.html_safe, root_path) %>
          </div>

          <%= render(partial: 'search_form')  %>
          <% if(logged_in?) %>
            <%= render(partial: 'authenticated_user_header') %>
          <% else %>
            <%= render(partial: 'anonymous_user_header') %>
          <% end %>
        </div>
      </div>
    </header>

    <%= yield %>

    <footer class="site-footer">
      <div class="content-wrapper">
        <div class="logo logo--inverted footer__logo">
          <%= link_to('<span><i>My</i> Bucket List</span>'.html_safe, root_path) %>
        </div>
        <nav class="footer__navigation">
          <ul>
            <li><a href="#nolink">About</a></li>
            <li><%= link_to('Style Guide', styles_atoms_path) %></li>
            <li><a href="#nolink">Terms of Use</a></li>
          </ul>
        </nav>
        <p class="copyright">&copy; EPFL 2017</p>
      </div>
    </footer>



  </body>
</html>